stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/interim
    - src/features/feature_engineering.py
    params:
    - feature_engineering.test_size
    - feature_engineering.num_classes
    - feature_engineering.random_state
    outs:
    - data/processed

  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    params:
    - model_building.embedding_dim
    - model_building.lstm_units
    - model_building.dropout
    - model_building.vocab_size
    - model_building.epochs
    - model_building.batch_size
    outs:
    - models/LSTM_512.h5

  model_evaluaton:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/LSTM_512.h5
    - src/model/model_evaluation.py
    params:
    - model_evaluaton.sample_size
    metrics:
    - reports/evaluation_metrics
    outs:
    - reports/model_info.json

  model_registration:
    cmd: python src/model/register_model.py
    deps:
    - reports/model_info.json
    - src/model/register_model.py